import {beforeEach,describe,expect,it} from "vitest";
import {resetWorld,getProvince} from "@/game/world/server/world-store";
import {resetMovement,createAIArmy,moveArmyForCountry} from "@/game/movement/server/movement-service";
import {resetAI,getAIStates,tickAI} from "@/game/ai/server/ai-engine";
import {resetWars,declareWar,attackProvince} from "@/game/war/server/war-service";
import {getClimate} from "@/game/world/server/climate-service";
import {weatherCombatModifier,weatherMovementModifier} from "@/game/world/server/weather-service";
import {pushAlert,getAlerts,resetAlerts} from "@/game/alerts/server/alert-store";
import {useGameStore} from "@/lib/game-store";
describe("phase 7 living world",()=>{beforeEach(()=>{resetWorld();resetMovement();resetAI();resetWars();resetAlerts();});
it("AI can produce army",()=>{tickAI(Date.now()+6000);expect(getAIStates().some(s=>s.countryId==="solaris")).toBe(true);expect(getAIStates().find(s=>s.countryId==="solaris")!.treasury).toBeLessThan(112000)});
it("AI can move army",()=>{const a=createAIArmy("verdant","nwc-06",1200);expect(moveArmyForCountry(a.id,"nwc-05").provinceId).toBe("nwc-05")});
it("AI can defend province",()=>{tickAI(Date.now()+6000);expect(getAIStates().find(s=>s.countryId==="solaris")!.priority).toMatch(/defend capital|produce army|attack weak enemy/) });
it("AI can attack",()=>{const a=createAIArmy("solaris","nwc-04",1200);const w=declareWar("solaris","aurora");expect(attackProvince(w.warId,a.id,"nwc-03",17).attackerArmyId).toBe(a.id)});
it("AI can occupy undefended province",()=>{const a=createAIArmy("verdant","nwc-06",1200);const moved=moveArmyForCountry(a.id,"nwc-08",true);expect(moved.provinceId).toBe("nwc-08");expect(getProvince("nwc-08")!.ownerId).toBe("verdant")});
it("AI cannot teleport",()=>{const a=createAIArmy("verdant","nwc-06",1200);expect(()=>moveArmyForCountry(a.id,"nwc-01")).toThrow(/adjacent/)});
it("AI cannot use infinite resources",()=>{tickAI(Date.now()+6000);const s=getAIStates().find(x=>x.countryId==="solaris")!;expect(s.manpower).toBeLessThan(5000);expect(s.steel).toBeLessThan(3000)});
it("climate affects province values",()=>{expect(getClimate("nwc-02")!.movementDifficulty).toBeGreaterThan(getClimate("nwc-03")!.movementDifficulty);expect(getClimate("nwc-02")!.agriculture).toBeLessThan(getClimate("nwc-03")!.agriculture)});
it("weather affects movement and combat",()=>{expect(weatherMovementModifier("blizzard")).toBeGreaterThan(weatherMovementModifier("clear"));expect(weatherCombatModifier("storm")).toBeLessThan(weatherCombatModifier("clear"))});
it("province selection triggers UI state",()=>{useGameStore.getState().selectProvince("nwc-03");expect(useGameStore.getState().selectedProvinceId).toBe("nwc-03")});
it("critical alerts trigger correctly and deduplicate",()=>{pushAlert({key:"capital-test",level:"critical",title:"CAPITAL UNDER ATTACK",message:"Test"});pushAlert({key:"capital-test",level:"critical",title:"CAPITAL UNDER ATTACK",message:"Test"});expect(getAlerts()).toHaveLength(1);expect(getAlerts()[0].level).toBe("critical")});});
