import {describe,it,expect,beforeEach} from "vitest"; import {getNation,getProvince,getDistricts,getPopulation,getCapitalState,setProvinceOwner,resetWorld} from "@/game/world/server/world-store";
describe("real world phase 9A foundation",()=>{beforeEach(()=>resetWorld());
it("four nations have capitals",()=>{for(const id of ["TR","DE","GB","RU"]){const n=getNation(id)!;expect(n.capitalProvinceId).toBeTruthy();expect(getProvince(n.capitalProvinceId)?.ownerId).toBe(id)}});
it("province belongs to Turkey",()=>{expect(getProvince("TR_ISTANBUL")?.countryId).toBe("TR")});
it("district belongs to province",()=>{expect(getDistricts("TR_ISTANBUL").every(d=>d.provinceId==="TR_ISTANBUL")).toBe(true)});
it("population cannot be negative",()=>{expect(getPopulation().every(p=>p.population>=0&&p.workers>=0&&p.soldiers>=0)).toBe(true)});
it("ownership transfer keeps province data",()=>{const p=getProvince("TR_ISTANBUL")!;const before=p.population;setProvinceOwner("TR_ISTANBUL","DE");expect(getProvince("TR_ISTANBUL")?.population).toBe(before)});
it("captured province keeps districts",()=>{setProvinceOwner("TR_ISTANBUL","DE");expect(getDistricts("TR_ISTANBUL").length).toBeGreaterThan(0)});
it("economy ownership remains queryable",()=>{setProvinceOwner("TR_ISTANBUL","DE");expect(getProvince("TR_ISTANBUL")?.ownerId).toBe("DE")});
it("capital loss changes state",()=>{setProvinceOwner("TR_ANKARA","DE");expect(getCapitalState("TR")?.lost).toBe(true)});
it("world map data loads",()=>{expect(getProvince("RU_MOSCOW")).toBeTruthy();expect(getDistricts().length).toBeGreaterThan(40)});
});