"use client";
import {useEffect,useMemo,useState} from "react"; import {Activity,Bell,Coins,Fuel,Hammer,Shield,Users} from "lucide-react";
import {WorldMap} from "@/components/map/WorldMap"; import {ProvincePanel} from "@/components/panels/ProvincePanel"; import {EconomyPanel} from "@/components/panels/EconomyPanel"; import {ProductionPanel} from "@/components/panels/ProductionPanel"; import {ConstructionPanel} from "@/components/panels/ConstructionPanel"; import {ArmyPanel} from "@/components/panels/ArmyPanel"; import {WarPanel} from "@/components/panels/WarPanel"; import {BattleResultPanel} from "@/components/panels/BattleResultPanel"; import {CountryPanel} from "@/components/panels/CountryPanel"; import {DistrictPanel} from "@/components/panels/DistrictPanel"; import {PopulationPanel} from "@/components/panels/PopulationPanel"; import {LivingWorldPanel} from "@/components/panels/LivingWorldPanel"; import {useGameStore} from "@/lib/game-store"; import {nations} from "@/data/world/countries"; import {getDistricts,getPopulation,getDevelopment,getResourcesMap} from "@/game/world/server/world-store";
const blank={id:"",name:"",ownerId:"",countryId:"",population:0,terrain:"plains" as const,neighbors:[],industryLevel:0,barracksLevel:0,fortificationLevel:0,infrastructureLevel:0,buildings:{industrialComplex:0,barracks:0,fortification:0},coordinates:[0,0] as [number,number],weather:"clear" as const};
export function GameScreen(){const selectedId=useGameStore(s=>s.selectedProvinceId),select=useGameStore(s=>s.selectProvince),provinces=useGameStore(s=>s.provinces),resources=useGameStore(s=>s.resources),income=useGameStore(s=>s.income),buildings=useGameStore(s=>s.provinceBuildings),production=useGameStore(s=>s.productionQueue),construction=useGameStore(s=>s.constructionQueue),armies=useGameStore(s=>s.armies),wars=useGameStore(s=>s.wars),battles=useGameStore(s=>s.battles);const load=useGameStore(s=>s.loadServerState),sync=useGameStore(s=>s.syncAll),startC=useGameStore(s=>s.startConstruction),startP=useGameStore(s=>s.startProduction),createArmy=useGameStore(s=>s.createArmy),declareWar=useGameStore(s=>s.declareWar),attack=useGameStore(s=>s.attack);const [living,setLiving]=useState<any>({ai:[],events:[],alerts:[],climate:[]});
 useEffect(()=>{void load();const id=setInterval(()=>void sync(),1500),world=setInterval(()=>fetch("/api/living-world",{cache:"no-store"}).then(r=>r.json()).then(setLiving).catch(()=>{}),2500);return()=>{clearInterval(id);clearInterval(world)}},[load,sync]);
 const base=provinces.find(p=>p.id===selectedId)??null,selected=base?{...base,buildings:buildings[base.id]??base.buildings}:null,activeWar=wars.find(w=>w.status==="active"),attackArmy=armies.find(a=>a.countryId==="aurora"&&a.status!=="destroyed"),country=selected?nations.find(n=>n.id===selected.ownerId):nations.find(n=>n.id==="aurora"),pop=selected?getPopulation(selected.id)[0]:undefined,dev=selected?getDevelopment(selected.id)[0]:undefined,resMap=selected?getResourcesMap(selected.id)[0]:undefined,districtList=selected?getDistricts(selected.id):[],alert=living.alerts?.[0],climate=living.climate?.find((c:any)=>c.provinceId===selected?.id);
 const doAttack=async()=>{if(activeWar&&attackArmy&&selected)await attack(activeWar.warId,attackArmy.id,selected.id)};
 return <main className="command-shell">{alert&&<div className={`critical-alert alert-${alert.level}`}><span>◆ {alert.title}</span><b>{alert.message}</b></div>}<header className="topbar"><div className="brand"><Shield size={19}/><span>NEXORA</span><b>WORLD COMMAND</b></div><div className="resources"><span><Coins/> {Math.round(resources.money).toLocaleString()}</span><span><Users/> {Math.round(resources.manpower).toLocaleString()}</span><span><Fuel/> {Math.round(resources.oil).toLocaleString()}</span><span><Hammer/> {Math.round(resources.steel).toLocaleString()}</span></div><div className="top-status"><Activity/> LIVE <span>SERVER TICK</span><Bell/></div></header>
 <section className="workspace"><aside className="left-panel"><div className="commander"><div className="avatar">NC</div><div><small>COMMANDER</small><strong>NEXORA COMMAND</strong><em>Living World Simulation</em></div></div>{["GLOBAL MAP","AI WAR ROOM","COUNTRIES","PROVINCES","DISTRICTS","ARMIES","ECONOMY","WAR","FRONTLINE"].map(x=><button className="nav" key={x}>{x}</button>)}<div className="side-card"><small>WORLD STATUS</small><strong>{activeWar?"WAR ACTIVE":"ACTIVE WORLD"}</strong><span>{provinces.length} provinces · {nations.length} nations · AI tick 5s</span></div></aside>
 <div className="map-wrap"><WorldMap provinces={provinces} selectedId={selectedId} onSelect={select}/><div className="map-overlay"><span>GLOBAL MAP · WORLD → COUNTRY → PROVINCE → DISTRICT</span><span>LIVE WEATHER · SERVER TICK</span></div></div>
 <ProvincePanel province={selected} onUpgrade={t=>selected&&startC(selected,t)} onInfantry={()=>selected&&startP(selected,"infantry")} onCreateArmy={()=>selected&&createArmy(selected.id)} onAttack={()=>void doAttack()}/></section>
 <section className="national-panels"><CountryPanel country={country} provinceCount={provinces.filter(p=>p.ownerId===country?.id).length}/><PopulationPanel province={selected} population={pop} development={dev} resources={resMap}/><DistrictPanel districts={districtList}/></section>
 <section className="lower-panels"><EconomyPanel resources={resources} income={income}/><ConstructionPanel province={selected??provinces[0]??blank} queue={construction} onUpgrade={t=>selected&&startC(selected,t)}/><ProductionPanel queue={production}/><ArmyPanel armies={armies} onMove={()=>{}}/><WarPanel wars={wars} battles={battles} onDeclare={d=>void declareWar(d)}/></section>
 <LivingWorldPanel data={living}/><BattleResultPanel battle={battles.at(-1)??null}/><footer className="newsbar"><strong>WORLD SIMULATION</strong><span>{selected?`${selected.name} // ${selected.weather.toUpperCase()} // CLIMATE ${climate?.band??"—"}`:"Select a province to inspect climate and weather"}</span><span>AI decisions are server-side and resource constrained.</span></footer></main>}
