import {getProvince,getWorld} from "@/game/world/server/world-store";
import type {Province} from "@/lib/types";
export type ClimateBand="arctic"|"tundra"|"temperate"|"tropical"|"desert"|"mediterranean";
export interface ClimateState{provinceId:string;band:ClimateBand;temperature:number;rainfall:number;agriculture:number;populationCapacity:number;movementDifficulty:number;resourceRichness:number}
const base:Record<ClimateBand,[number,number,number,number,number,number]>={arctic:[-18,180,8,12,92,35],tundra:[-5,320,18,28,78,40],temperate:[14,700,72,78,34,62],tropical:[27,1500,84,88,28,58],desert:[30,80,10,22,70,82],mediterranean:[18,520,68,70,36,65]};
function bandFor(p:Province):ClimateBand{if(p.countryId==="TR")return p.terrain==="mountain"?"tundra":"mediterranean";if(p.countryId==="RU")return p.terrain==="mountain"||p.name==="Saint Petersburg"?"tundra":"temperate";if(p.countryId==="GB"||p.countryId==="DE")return "temperate";return "temperate"}
export function getClimate(provinceId:string):ClimateState|undefined{const p=getProvince(provinceId);if(!p)return;const band=bandFor(p);const [temperature,rainfall,agriculture,populationCapacity,movementDifficulty,resourceRichness]=base[band];const terrain=p.terrain;const terrainPenalty=terrain==="mountain"?18:terrain==="forest"?8:terrain==="coast"?-4:terrain==="urban"?-8:terrain==="hills"?10:0;return{provinceId,band,temperature,rainfall,agriculture:Math.max(0,agriculture-terrainPenalty),populationCapacity:Math.max(10,populationCapacity-terrainPenalty),movementDifficulty:Math.min(100,Math.max(5,movementDifficulty+terrainPenalty)),resourceRichness}}
export function getClimateMap(){return getWorld().map(p=>getClimate(p.id)).filter(Boolean) as ClimateState[]}
export function climateMovementCost(p:Province){return getClimate(p.id)?.movementDifficulty??40}
