"use client";
import {useMemo,useState} from "react";
import type {Province} from "@/lib/types";
import type {Army} from "@/game/movement/server/types";
import {countries} from "@/data/provinces";
import {audioManager} from "@/lib/audio-manager";
export type MapMode="political"|"population"|"economy"|"resources"|"military"|"weather"|"terrain"|"frontline";
const terrainFill:Record<string,string>={plains:"#65765d",forest:"#405b4b",mountain:"#66645b",urban:"#56605f",coast:"#4e695f",desert:"#88764d",tundra:"#68757a"};
const modeLabel:Record<MapMode,string>={political:"POLITICAL",population:"POPULATION",economy:"ECONOMY",resources:"RESOURCES",military:"MILITARY",weather:"WEATHER",terrain:"TERRAIN",frontline:"FRONTLINE"};
function UnitGlyph({army,large=false}:{army:Army;large?:boolean}){const armored=army.tanks>0;return <g className={`unit-glyph ${large?"large":""} ${armored?"armored":"infantry"}`}><rect x="-3.8" y="-3.8" width="7.6" height="7.6" rx="1"/><text x="0" y="1.5" textAnchor="middle">{armored?"▰":"✚"}</text><text x="0" y="7" textAnchor="middle" className="unit-count">{army.strength>999?`${Math.round(army.strength/1000)}K`:army.strength}</text></g>}
export function WorldMap({provinces,armies,selectedId,selectedArmyId,onSelect,onSelectArmy,mapMode,onMapModeChange}:{provinces:Province[];armies:Army[];selectedId:string|null;selectedArmyId:string|null;onSelect:(id:string)=>void;onSelectArmy:(id:string)=>void;mapMode:MapMode;onMapModeChange:(mode:MapMode)=>void}){
 const [zoom,setZoom]=useState(1);const selected=provinces.find(p=>p.id===selectedId);const selectedArmy=armies.find(a=>a.id===selectedArmyId);const maxPop=Math.max(...provinces.map(p=>p.population),1);const maxInd=Math.max(...provinces.map(p=>p.industryLevel),1);
 const fill=(p:Province)=>{if(mapMode==="population")return `hsl(38 55% ${28+(p.population/maxPop)*28}%)`;if(mapMode==="economy")return `hsl(143 32% ${22+(p.industryLevel/maxInd)*28}%)`;if(mapMode==="terrain")return terrainFill[p.terrain]??"#566";if(mapMode==="weather")return p.weather==="snow"||p.weather==="blizzard"?"#81949b":p.weather==="heatwave"?"#866148":p.weather==="storm"?"#4f566b":"#53685a";if(mapMode==="military")return armies.some(a=>a.provinceId===p.id)?"#80683e":"#3c4b48";return countries.find(c=>c.id===p.ownerId)?.color??"#586168"};
 const shape=(x:number,y:number)=>`${x-7},${y-4} ${x-2},${y-8} ${x+6},${y-5} ${x+8},${y+2} ${x+3},${y+8} ${x-5},${y+6} ${x-8},${y}`;
 const path=useMemo(()=>{if(!selectedArmy)return null;const from=provinces.find(p=>p.id===selectedArmy.provinceId);const to=selected?selected:provinces.find(p=>p.id===selectedArmy.provinceId);if(!from||!to)return null;return {x1:from.coordinates[0],y1:from.coordinates[1],x2:to.coordinates[0],y2:to.coordinates[1]};},[selectedArmy,selected,provinces]);
 return <div className="world-map"><div className="map-vignette"/><div className={`weather-layer weather-${selected?.weather??"clear"}`}/><div className="map-header"><b>WORLD THEATRE</b><span>{modeLabel[mapMode]} {"//"} {zoom.toFixed(1)}×</span><span>PROVINCES {provinces.length}</span></div><div className="map-compass">N<br/><i>＋</i></div>
 <svg viewBox="0 0 100 100" className="province-map" style={{transform:`scale(${zoom})`}}><path d="M3 13 Q14 5 28 11 T49 8 Q62 3 76 12 T96 16 L93 42 Q85 50 91 63 T80 93 Q63 98 49 88 T28 94 Q14 87 9 72 T4 50Z" className="landmass"/>{provinces.map(p=>{const[x,y]=p.coordinates,isSelected=p.id===selectedId,country=countries.find(c=>c.id===p.ownerId);return <g key={p.id} className={`province-territory ${isSelected?"selected":""}`} onClick={()=>{audioManager.provinceSelected();onSelect(p.id)}}><polygon points={shape(x,y)} fill={fill(p)} className="province-shape"/><polyline points={shape(x,y)+" "+shape(x,y)} className="province-border"/><text x={x} y={y+1} textAnchor="middle" className="province-label">{p.name}</text>{country?.capitalProvinceId===p.id&&<text x={x} y={y-6} textAnchor="middle" className="capital-mark">★</text>}{mapMode==="military"&&armies.filter(a=>a.provinceId===p.id).map((a,i)=><g key={a.id} transform={`translate(${x+i*4-4},${y+5})`} onClick={e=>{e.stopPropagation();onSelectArmy(a.id)}}><UnitGlyph army={a}/></g>)}</g>})}{path&&path.x1!==path.x2&&<path d={`M ${path.x1} ${path.y1} Q ${(path.x1+path.x2)/2} ${Math.min(path.y1,path.y2)-8} ${path.x2} ${path.y2}`} className="movement-path"/>}{armies.map(a=>{const p=provinces.find(q=>q.id===a.provinceId);if(!p||mapMode!=="military")return null;return <g key={`u-${a.id}`} transform={`translate(${p.coordinates[0]+6},${p.coordinates[1]-5})`} className={`army-marker ${a.id===selectedArmyId?"army-selected":""}`} onClick={e=>{e.stopPropagation();audioManager.provinceSelected();onSelectArmy(a.id)}}><UnitGlyph army={a} large={a.id===selectedArmyId}/></g>})}</svg>
 <div className="map-modebar">{(Object.keys(modeLabel) as MapMode[]).map(m=><button key={m} className={mapMode===m?"active":""} onClick={()=>onMapModeChange(m)}>{modeLabel[m]}</button>)}</div><div className="map-controls"><button onClick={()=>setZoom(z=>Math.min(1.7,z+.15))}>＋</button><button onClick={()=>setZoom(z=>Math.max(1,z-.15))}>−</button><button onClick={()=>setZoom(1)}>⌖</button></div><div className="map-legend"><span><i className="legend-infantry"/>INF</span><span><i className="legend-armored"/>ARM</span><span><i className="legend-capital">★</i>CAPITAL</span><span>SHIFT+CLICK: ORDER</span></div><div className="map-weather">{"WEATHER // "}{(selected?.weather??"clear").toUpperCase()}</div></div>}
