"use client";
import {FormEvent,useEffect,useState} from "react";
import {Radio,Shield,Check,ArrowRight,UserPlus,LogIn,WifiOff,LockKeyhole} from "lucide-react";
import {useRouter} from "next/navigation";
import {REAL_WORLD_COUNTRIES,REAL_WORLD_PROVINCES} from "@/data/world/real-world-provinces";
const KEY="nwc-commander-callsign",COUNTRY_KEY="nwc-player-country",PROFILE_KEY="nwc-commander-profile",MODE_KEY="nwc-session-mode",GUEST_KEY="nwc-guest-session";
type Mode="login"|"register"|"guest";
export function CommanderEntry(){
 const router=useRouter();const [mode,setMode]=useState<Mode>("login");const [step,setStep]=useState<"auth"|"identity"|"nation">("auth");
 const [username,setUsername]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[callsign,setCallsign]=useState("");
 const [country,setCountry]=useState<string|null>(null),[profile,setProfile]=useState("default"),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem(KEY),savedCountry=localStorage.getItem(COUNTRY_KEY),savedMode=localStorage.getItem(MODE_KEY);if(saved&&savedCountry&&savedMode==="online")router.replace("/game");},[router]);
 const auth=async(e:FormEvent)=>{e.preventDefault();setError("");if(mode==="guest"){startGuest();return}if(password.length<8)return setError("Şifre en az 8 karakter olmalı.");if(mode==="register"&&password!==confirm)return setError("Şifreler eşleşmiyor.");setBusy(true);try{const r=await fetch("/api/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode,username,password})});const p=await r.json();if(!r.ok)throw new Error(p.error);localStorage.setItem("nwc-account-id",p.account.id);localStorage.setItem("nwc-account-username",p.account.username);setStep("identity");}catch(e){setError(e instanceof Error?e.message:"Giriş başarısız.")}finally{setBusy(false)}};
 const startGuest=()=>{const now=Date.now();localStorage.setItem(MODE_KEY,"guest");localStorage.setItem(GUEST_KEY,JSON.stringify({startedAt:now,maxDay:3}));setCallsSign("GUEST COMMANDER");setStep("nation")};
 const setCallsSign=(v:string)=>{setCallsign(v);localStorage.setItem(KEY,v)};
 const submitIdentity=(e:FormEvent)=>{e.preventDefault();const v=callsign.trim();if(v.length<3)return;setCallsSign(v);setStep("nation")};
 const enter=async()=>{if(!country)return;localStorage.setItem(COUNTRY_KEY,country);localStorage.setItem(PROFILE_KEY,profile);localStorage.setItem(MODE_KEY,mode==="guest"?"guest":"online");localStorage.removeItem("nwc-newspaper-seen");if(mode!=="guest")await fetch("/api/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({mode:"recordGame",type:"GAME_ENTER"})});router.replace("/game")};
 const nation=REAL_WORLD_COUNTRIES.find(c=>c.id===country);
 return <main className="commander-entry"><div className="entry-grid"/><section className="entry-card wide-entry">
 <div className="entry-brand"><strong>NEXORA</strong><span>WORLD COMMAND</span></div><div className="entry-mark"><Shield/></div>
 {step==="auth"&&<><p className="entry-kicker">SECURE COMMAND NETWORK</p><h1>{mode==="login"?"COMMAND LOGIN":mode==="register"?"CREATE COMMAND ACCOUNT":"GUEST CAMPAIGN"}</h1>
 <div className="entry-tabs"><button onClick={()=>{setMode("login");setError("")}} className={mode==="login"?"active":""}><LogIn/> GİRİŞ</button><button onClick={()=>{setMode("register");setError("")}} className={mode==="register"?"active":""}><UserPlus/> HESAP OLUŞTUR</button><button onClick={()=>{setMode("guest");setError("")}} className={mode==="guest"?"active":""}><WifiOff/> MİSAFİR OYNA</button></div>
 {mode==="guest"?<div className="guest-warning"><WifiOff/><b>SADECE ÇEVRİMDIŞI</b><span>Misafir kampanyası internete bağlanmaz ve en fazla 3 oyun günü sürer. Kayıtlı çevrimiçi dünya için hesap oluşturun.</span></div>:
 <form onSubmit={auth}><label>KULLANICI ADI</label><input value={username} onChange={e=>setUsername(e.target.value)} minLength={3} maxLength={20} pattern="[A-Za-z0-9_]+" required placeholder="COMMANDER_ID"/><label>ŞİFRE</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required placeholder="MIN. 8 CHARACTERS"/>{mode==="register"&&<><label>ŞİFRE TEKRAR</label><input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={8} required/></>}<button disabled={busy}>{busy?"AUTHENTICATING...":mode==="login"?"GİRİŞ YAP":"HESAP OLUŞTUR"} <ArrowRight/></button></form>}
 {mode==="guest"&&<button className="entry-primary" onClick={auth}><WifiOff/> MİSAFİR KAMPANYASINI BAŞLAT <ArrowRight/></button>}{error&&<p className="entry-error">{error}</p>}
 </>}
 {step==="identity"&&<><p className="entry-kicker">AUTHENTICATED COMMANDER</p><h1>COMMAND IDENTITY</h1><p className="entry-copy">Choose the callsign shown across your command interface.</p><form onSubmit={submitIdentity}><label>CALLSIGN</label><input value={callsign} onChange={e=>setCallsSign(e.target.value)} minLength={3} maxLength={20} required autoFocus placeholder="COMMANDER NAME"/><div className="profile-choice"><button type="button" className={profile==="default"?"profile-option active":"profile-option"} onClick={()=>setProfile("default")}>PLAYER COMMANDER</button><button type="button" className={profile==="ataturk"?"profile-option active":"profile-option"} onClick={()=>setProfile("ataturk")}><img src="/portraits/ataturk.png" alt=""/> HISTORICAL PROFILE</button></div><button><Radio/> CONTINUE <ArrowRight/></button></form></>}
 {step==="nation"&&<><p className="entry-kicker">{mode==="guest"?"OFFLINE GUEST CAMPAIGN":"ONLINE COMMAND NETWORK"} · {callsign.toUpperCase()}</p><h1>SELECT YOUR NATION</h1><p className="entry-copy">{mode==="guest"?"Bu kampanya yalnızca cihazında çalışır. En fazla 3 oyun günü.":"Hesabın çevrimiçi oyun kayıtları ve tarihçesi için kullanılacak."}</p><div className="nation-grid">{REAL_WORLD_COUNTRIES.map(c=><button type="button" key={c.id} className={country===c.id?"nation-card active":"nation-card"} onClick={()=>setCountry(c.id)}><span className="nation-code"><img src={"/flags/"+c.id+".png"} alt="" onError={e=>{e.currentTarget.style.display="none"}}/><span>{c.flag}</span></span><div><strong>{c.displayName}</strong><small>{c.name}</small></div>{country===c.id&&<Check/>}</button>)}</div>{nation&&<div className="nation-confirm"><div><small>NATION SELECTED</small><b>{nation.displayName}</b><span>CAPITAL · {nation.capitalProvinceId} · {Object.values(REAL_WORLD_PROVINCES).filter(p=>p.countryCode===nation.id).length} PROVINCES</span></div><button type="button" onClick={enter}><Radio/> {mode==="guest"?"PLAY OFFLINE":"ENTER ONLINE WORLD"}</button></div>}</>}
 </section></main>;
}