"use client";

import { X, Coins, Swords, FlaskConical, Eye, Handshake, Factory, Route, MessageSquare } from "lucide-react";
import {useEffect,useState} from "react";
import {audioManager} from "@/lib/audio-manager";
import type { Army } from "@/game/movement/server/types";
import type { Province } from "@/lib/types";
import type { Resources } from "@/data/economy/resources";
import { nations } from "@/data/world/countries";

export type CommandScreenId="DIPLOMACY"|"ECONOMY"|"MILITARY"|"RESEARCH"|"INTELLIGENCE"|"EXPEDITIONS"|"MESSAGES";
type Props={screen:CommandScreenId;onClose:()=>void;provinces:Province[];armies:Army[];resources:Resources;income:Resources};
const techs=[["INFANTRY","Improved Rifles","Mechanized Infantry","Advanced Infantry"],["ARMOR","Light Tanks","Medium Tanks","Main Battle Tanks"],["AIR","Fighters","Bombers","Recon Aircraft"]];

export function CommandScreen({screen,onClose,provinces,armies,resources,income}:Props){
 useEffect(()=>{audioManager.menuOpened()},[screen]);
 const [refresh,setRefresh]=useState(0); useEffect(()=>{const t=setInterval(()=>setRefresh(x=>x+1),3000);return()=>clearInterval(t)},[]);
 const [messages,setMessages]=useState<any[]>([]),[relations,setRelations]=useState<any[]>([]),[research,setResearch]=useState<any[]>([]);
 useEffect(()=>{if(screen==="MESSAGES")fetch("/api/command?type=messages").then(r=>r.json()).then(x=>setMessages(x.messages??[]));if(screen==="DIPLOMACY")fetch("/api/command?type=diplomacy").then(r=>r.json()).then(x=>setRelations(x.relations??[]));if(screen==="RESEARCH")fetch("/api/command?type=research").then(r=>r.json()).then(x=>setResearch(x.research??[]))},[screen,refresh]);
 const command=async(body:any)=>{const r=await fetch("/api/command",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok)throw new Error(x.error);setRefresh(v=>v+1);return x};
 const title=screen==="DIPLOMACY"?"DIPLOMATIC COMMAND":screen+" COMMAND";
 return <div className="command-overlay"><section className="command-screen"><header><div><small>WORLD COMMAND // SYSTEMS</small><h1>{title}</h1></div><button onClick={onClose}><X/></button></header>
 {screen==="DIPLOMACY"&&<Diplomacy provinces={provinces} relations={relations} onAction={command}/>}
 {screen==="ECONOMY"&&<Economy resources={resources} income={income} provinces={provinces}/>}
 {screen==="MILITARY"&&<Military armies={armies}/>}
 {screen==="RESEARCH"&&<Research data={research} onResearch={command}/>}{screen==="INTELLIGENCE"&&<Intelligence provinces={provinces} armies={armies}/>} {screen==="EXPEDITIONS"&&<Expeditions provinces={provinces}/>} {screen==="MESSAGES"&&<Messages data={messages} onRead={command}/>}
 </section></div>;
}
function Diplomacy({provinces,relations,onAction}:{provinces:Province[];relations:any[];onAction:(b:any)=>Promise<any>}){return <div className="command-grid"><div className="command-card command-wide"><h2><Handshake/> DIPLOMATIC RELATIONS</h2><div className="country-table">{nations.filter(n=>n.id!=="TR").map(n=>{const r=relations.find(x=>(x.from==="TR"&&x.to===n.id)||(x.from===n.id&&x.to==="TR"));return <div key={n.id}><b>{n.displayName}</b><span>RELATION · {r?.score??0} · {(r?.status??"neutral").toUpperCase()}</span><em>{r?.alliance?"ALLIANCE":r?.nonAggression?"NON-AGGRESSION":r?.trade?"TRADE":"NO TREATY"}</em><button onClick={()=>void onAction({type:"relation",from:"TR",to:n.id,action:"improve"})}>IMPROVE</button><button onClick={()=>void onAction({type:"relation",from:"TR",to:n.id,action:"trade"})}>TRADE</button></div>})}</div></div></div>;}
function Economy({resources,income,provinces}:{resources:Resources;income:Resources;provinces:Province[]}){return <div className="command-grid"><div className="command-card command-wide"><h2><Coins/> NATIONAL ECONOMY</h2><div className="metric-grid">{Object.entries(resources).map(([k,v])=><div key={k}><small>{k.toUpperCase()}</small><b>{Math.round(v).toLocaleString()}</b><span>+{Math.round(income[k as keyof Resources]??0).toLocaleString()}/h</span></div>)}</div></div><div className="command-card"><h2><Factory/> INDUSTRIAL OUTPUT</h2><p>{provinces.reduce((s,p)=>s+p.industryLevel,0)} total industry levels across {provinces.length} provinces.</p><p>Existing economy actions remain server-authoritative.</p></div></div>;}
function Military({armies}:{armies:Army[]}){const infantry=armies.reduce((s,a)=>s+a.infantry,0),tanks=armies.reduce((s,a)=>s+a.tanks,0);return <div className="command-grid"><div className="command-card command-wide"><h2><Swords/> FORCE REGISTER</h2><div className="metric-grid"><div><small>ARMIES</small><b>{armies.length}</b></div><div><small>INFANTRY</small><b>{infantry.toLocaleString()}</b></div><div><small>ARMOR</small><b>{tanks.toLocaleString()}</b></div><div><small>STRENGTH</small><b>{armies.reduce((s,a)=>s+a.strength,0).toLocaleString()}</b></div></div></div><div className="command-card"><h2>READINESS</h2>{armies.map(a=><div className="readiness-row" key={a.id}><span>{a.name}</span><b>{a.morale}%</b></div>)}</div></div>;}
function Research({data,onResearch}:{data:any[];onResearch:(b:any)=>Promise<any>}){return <div className="command-grid research-grid">{data.map(t=><div className="command-card" key={t.id}><h2><FlaskConical/> {t.branch}</h2><button className="tech-node" disabled={t.status!=="available"} onClick={()=>{audioManager.technologySelected();void onResearch({type:"research",id:t.id})}}><span>{t.progress}%</span><div><b>{t.name}</b><small>{t.status.toUpperCase()}</small></div></button></div>)}</div>;}
function Expeditions({provinces}:{provinces:Province[]}){return <div className="command-grid"><div className="command-card command-wide"><h2><Route/> EXPEDITION REGISTER</h2><p>Strategic routes and field movements are collected here. {provinces.length} provinces are currently available to the command theatre.</p></div><div className="command-card"><h2>ROUTE STATUS</h2><p>LIVE · SERVER SYNCHRONIZED</p></div></div>}
function Messages({data,onRead}:{data:any[];onRead:(b:any)=>Promise<any>}){return <div className="command-grid"><div className="command-card command-wide"><h2><MessageSquare/> COMMAND MESSAGES</h2>{data.map(m=><button className={`message-row ${m.read?"read":"unread"}`} key={m.id} onClick={()=>void onRead({type:"read",id:m.id})}><b>{m.title}</b><span>{m.body}</span><small>{m.category.toUpperCase()} · {new Date(m.createdAt).toLocaleTimeString()}</small></button>)}</div></div>}
function Intelligence({provinces,armies}:{provinces:Province[];armies:Army[]}){return <div className="command-grid"><div className="command-card command-wide"><h2><Eye/> INTELLIGENCE PICTURE</h2><div className="metric-grid"><div><small>PROVINCES OBSERVED</small><b>{provinces.length}</b></div><div><small>KNOWN ARMIES</small><b>{armies.length}</b></div><div><small>SPY NETWORK</small><b>LOCAL DATA ONLY</b></div></div></div><div className="command-card"><h2>COUNTER INTELLIGENCE</h2><p>No spy deployment backend exists yet. The panel intentionally exposes no fake action.</p></div></div>;}
