export const WAR_TRANSACTION_REASONS = {
 BATTLE_CASUALTY:"BATTLE_CASUALTY",
 PROVINCE_CAPTURE:"PROVINCE_CAPTURE",
} as const;
export type WarTransactionReason = typeof WAR_TRANSACTION_REASONS[keyof typeof WAR_TRANSACTION_REASONS];
